### ISSUE TITLE
Implementation Results of axi4 wrapped core

### ISSUE THREAD

**Issue by Sanjay-A-Menon** [secworks/sha256#15]
I have implemented a block design with the packaged IP. I had a few doubts:-

1. How did you calculate the different parameters you have mentioned in your README.md such as SLICES, no:of registers, no: of LUT's etc from the implementation report in Vivado?.

2. How did you implement a block design with the IP without using an AXI4 wrapped interface?(Since PS-PL communication for a ZYNQ architecture requires an AXI4 interface either stream, lite or full)

Attached is my implementation utilization report of the Block design on PYNQ-Z2 using the AXI4 wrapped SHA256 IP.

Implementation details :-
- PYNQ-Z2(xc7z020clg400-1)
- Clock:- 75 MHz

I found out that the max frequency at which the design can operate without any timing violations is 78.89 MHz found using the formula Fmax = 1/(Expected Time Period - WNS).
WNS - Worst Negative Slack

How do I optimize the design for better speed?

[SHA256_impl_rpt.txt](https://github.com/secworks/sha256/files/4438453/SHA256_impl_rpt.txt)

**Comment by secworks** [comment]
Hi!
Very sorry for a **very slow** response. Great of you to provide the report. I will include it in the README.

The numbers I have is directly from Vivado, with the original top level wrapper. You don't need to bridge with PS-PL to use the FPGA fabric in the device. (The core can connect to external I/Os.)

Regarding speed. You can increase clock speed by pipelining/dividing the round processing. There are some long paths with multiple arithmetic operations there. But note, that this will directly double (pr more) the number of cycles required to process one message block. So, you will gain clock speed, but unless you gain > 2x clock frequency, you will loose performance. If you want better performance, you basically need to pipeline the rounds so that the core is able to process more than one message block at a time. This will require instantiating multiple block schedule modules.

**Comment by secworks** [comment]
I have now updated the README with your implementation results. Thanks!
