### ISSUE TITLE
Redundant counter

### ISSUE THREAD

**Issue by ZhengsenF** [secworks/sha256#17]
The counter `t_ctr_reg` in `sha256_core.v: line 125` counts the same thing as `w_ctr_reg` in `sha256_w_mem.v: line 76`. It should be safe to delete one of them and pass the signal to the other one.

**Comment by secworks** [comment]
Interesting observation, thanks for pointing that out. I will investigate.

It would probably make most sense to remove the counter i w_mem. The core would order/control which words in the message block it wanted from the scheduler.

**Comment by secworks** [comment]
I took a look at the code, and you are absolutely right. The counter is only used to select which word to use for the first 16 rounds. And for subseqent rounds, just as a flag. This means that one could use the round counter in sha256_core. One could also just use four counter bits and a separate signal to indicate subsequent rounds. Saving at least one wire.

Implementing this will require some rework of the testbench for sha256_w_mem, but otherwise just some ports and wires in sha256_core.v I'll probably do this in a couple of days.

**Comment by secworks** [comment]
I implemented the suggested sharing of couter in commit https://github.com/secworks/sha256/commit/93d7f301f1909a01a0130834a88c3a0b5b8f20be

Thanks @ZhengsenF for the suggestion!
