### ISSUE TITLE
Performance in the SKY130 process

### ISSUE THREAD

**Issue by kralux** [secworks/sha256#21]
Hi Joachim, great work and thank you for making this public.
Could you give me an idea of the speed that could be achievable in the SKY130 process?
I am mostly interested in what the max clock freq could be (assuming I control the temperature to < 30C with fans) and how many clock cycles it would take to hash a single block. I don't care about the latency, only the performance in terms of throughput. 
Thank you! Alex.

**Comment by secworks** [comment]
Hi Alex!

Good question. I don't have any good number on clock frequency reached with SKY130. My guess is between 100 and 200 MHz. Since the number of clock cycles to process one block is 66 cycles. You should be able to process 1.5 and 3.0 millions blocks/s.

**Comment by secworks** [comment]
If the problem is possible to parallelize (like Bitcoing mining) you can of course run several cores in parallel. This core has beern used in a number of mining ASICs like this.

**Comment by Alex-Kral** [comment]
yes I am thinking of placing as many in parallel as possible. However, can you think of a way to make it faster than taking 66 cycles per hashed block?  I am wondering if there is anything that can be done to make it much faster without taking as much room as 66 equivalent cores... Any thoughts on that would be greatly appreciated. 
One last question: what is a ballpark consumption for this circuit if it ran at 200 MHz on the SKY130 process? Order of magnitude is fine... 
Thank you Joachim!

**Comment by secworks** [comment]
You could possibly shave off a cycle. But a latency below 64 cycles means more than one round per cycle. That would seriously drop the clock frequency, and you would increase size, since you would up with a block-memory with many ports. This is imho why you don't see SHA256 HW implementations with radically lower latency than one round/cycle.

But the size of the core isn't that large, so you should be able to instantiate a lot of cores.

I have unfortunately a ballpark guess on power consumption.
